name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Tests
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic imports
      run: |
        python3 -c "import app; print('✅ App import successful')"
        python3 -c "import latex_converter; print('✅ LatexConverter import successful')"
        python3 -c "import your_model_utils; print('✅ Model utils import successful')"
    
    - name: Run pytest
      run: |
        pytest tests/test_app.py tests/test_latex_converter.py tests/test_model_utils.py -v --tb=short
      env:
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key-for-ci

  # Code Quality
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || true
    
    - name: Run black check
      run: |
        black --check --diff . || true
    
    - name: Run isort check
      run: |
        isort --check-only --diff . || true

  # Matrix Tests (Python 3.9, 3.10)
  test-matrix:
    name: Matrix Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/test_app.py tests/test_latex_converter.py tests/test_model_utils.py -v --tb=short
      env:
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key-for-ci